app_id: "<app id>" 
app_secret: "<client secret>" 
redirect: "http://localhost:8000/callback" 
scopes:   
    - user.read   
    - mailboxsettings.read   
    - calendars.readwrite 
    - Calendars.Read
authority: "https://login.microsoftonline.com/<tenant id>"
